# Generated by Django 4.1.1 on 2022-12-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_fetch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='camera_brand_and_model',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
