# Generated by Django 4.1.1 on 2022-12-12 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta_fetch', '0002_image_camera_brand_and_model_image_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('file_title', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('keywords', models.CharField(blank=True, max_length=50, null=True)),
                ('producing_aplication', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateField(auto_now=True)),
                ('modified', models.DateField(auto_now=True)),
                ('hidden_layers', models.IntegerField()),
                ('copyright_info', models.IntegerField()),
                ('attached_files', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('camera_brand_and_model', models.CharField(default=0, max_length=50)),
                ('size', models.IntegerField()),
                ('aperture', models.CharField(blank=True, max_length=50, null=True)),
                ('shutter_speed', models.CharField(blank=True, max_length=50, null=True)),
                ('iso', models.CharField(blank=True, max_length=50, null=True)),
                ('focal_depth', models.CharField(blank=True, max_length=50, null=True)),
                ('image_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('dot_per_inch', models.CharField(blank=True, max_length=50, null=True)),
                ('color_profile', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_fetch.uimage')),
            ],
        ),
        migrations.CreateModel(
            name='UserPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_fetch.pdf')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AddField(
            model_name='userpdf',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_fetch.user'),
        ),
        migrations.AddField(
            model_name='userimage',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_fetch.user'),
        ),
    ]
