# Generated by Django 4.1.1 on 2022-12-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_fetch', '0003_pdf_uimage_userimage_userpdf_remove_user_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UImage',
            new_name='I_mage',
        ),
    ]
