# Generated by Django 4.1.1 on 2022-12-12 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta_fetch', '0004_rename_uimage_i_mage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateField(auto_now=True)),
                ('modified', models.DateField(auto_now=True)),
                ('field', models.CharField(blank=True, max_length=50, null=True)),
                ('header', models.CharField(blank=True, max_length=50, null=True)),
                ('encoding', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='J_son',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateField(auto_now=True)),
                ('modified', models.DateField(auto_now=True)),
                ('model_id', models.IntegerField()),
                ('model_label', models.CharField(blank=True, max_length=50, null=True)),
                ('model_description', models.CharField(blank=True, max_length=50, null=True)),
                ('model_category', models.CharField(blank=True, max_length=50, null=True)),
                ('associated_imagefile', models.ImageField(upload_to=None)),
                ('associated_thumbnail_imagefile', models.ImageField(upload_to=None)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('attributes', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_fetch.j_son')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_fetch.user')),
            ],
        ),
    ]
